### ISSUE TITLE
Multipurpose board - комментарии с ротацией.

### ISSUE THREAD

**Issue by georgy7** [denpamedia/minichan#1]
У меня для тебя Feature Request.
Сделай рефакторинг по хардкору, чтобы можно было использовать так:
У тебя есть сайт/блог, у которого есть страницы со статьями. Требуется, чтобы у каждой страницы подключались комменты, но комменты эти были с ротацией.

Тогда коммент - это Original post, ответ на коммент (пока не нужно) - обычный post.
Все комменты к странице - борда.

Нужно централизованно указать количество Original post на страницу.
Получается, что страница со статьей будет микробордой, а на сайте будет много текстовых микроборд (до нескольких тысяч).

Встраивание можно делать через iframe (так можно в микс с сайтами на php/java), главное, чтобы на произвольную страницу домена можно было вставить обычным хтмл без необходимости что-то специально вносить в бд.

**Comment by a-stringfield** [comment]
Интересная идея, такая Board as a Service.
Только стоит ли делать комменты Original Post'ами? Мне кажется, куда логичней сделать статью/пост в блоге OP, а комменты - это реплаи.
Или я не правильно тебя понял?

**Comment by georgy7** [comment]
Суть в том, чтобы дать позвможность совместить твою борду с вообще любым произвольным движком. Например, блог на вордпрессе есть у кого-то - там нет никаких твоих Original Post, а посты уже есть. Он думает, надо комменты, но стандартные нипайдёт. Он берет твою борду, ставит на тот же хостинг и м.б. даже в ту же базу (таблицы с префиксом), и в шаблон статьи в вордпрессе ставит iframe src /board/comments. В ифрейм страница пока подгружается, выясняет, какой url у той страницы, в которой iframe, и он воспринимается, как идентификатор борды (т.е. как разделы /b/, /c/, /pr/, /мпх/ на двачах, вместо них "/article/12345"). Если кто-то создает там пост, он сохраняется вот с такими пометками в базе, и соответственно, показываются тоже по такому же фильтру, чтобы у каждой статьи как будто борда отдельная.

Или такой вариант (мне даже больше нравится):
Можно передавать идентификатор статьи/поста или произвольную другую лажу в url ифрейма, что позволит делать разные комментарии к нескольким постам на странице. iframe src="/board/comments/12345".
Это также позволит делать какие-то безумные вещи. Например, борда на категорию, борда на тег. Как разраб решит, что использовать в качестве ключа, то и сделает. Получится суперуниверсальная штука.

**Comment by georgy7** [comment]
Короче, я предлагаю, что статья - это раздел, а коммент - ОП, а коммент коммента - пост. 

В общем решать тебе. Может быть ты разовьешь движок во что-то совершенно другое. Действительно, взять да и заделать сложную верстку и множественные картинки в ОП-посты или интеграцию с постами популярных CMS - получится абсолютно безумная вещь, борда-монстр.

**Comment by aslian** [comment]
Не придумывай чепухи и подключи уже себе http://disqus.com/

**Comment by a-stringfield** [comment]
Я тоже поразмышлял, и понял, что получится просто система комментирования, которых уже дохера.
Да и смысл на каждую статью под комменты отдельную борду заводить? Это что за статьи должны быть, чтобы на их обсуждение требовалась целая борда?
Лучше оставить минимальный функционал, характерный для АИБ, и довести его до ума. Ну и добавить свистелки-перделки с джаваскриптом и каким-нибудь модным CSS-фреймворком (а то бутстрап все что-то обосрали).

**Comment by r00takaspin** [comment]
В связи с новым законом о сми - было бы крайне удобно сделать подобный сервис. Скажем, комментарии живут максимум сутки, все данные о комментаторах и комментарии удаляются через какое-то время. 

Но для этого нужно как минимум два человека:
1) один сверстает все под любое разрешение, чтобы все отображалось так же круто как на disqus
2) js-сукин сын, который сделает фактически standalone скрипт для комментирования

**Comment by a-stringfield** [comment]
Они же, вроде, сами как-то собираются определять количество читателей? То есть, удаляющиеся комменты не особо помогут.

**Comment by r00takaspin** [comment]
Я говорю, как раз, про комментарии - то есть они будут лежать у нас на сервисе, и за то что происходит в комментариях СМИ не будут нести никакой отвественности.

**Comment by a-stringfield** [comment]
Нужно перечитать последние публикации об этих законах. Я не уверен, что это поможет в случае чего. Принесут в суд скриншот шатающего скрепы коммента под постом, и доказывай им потом, что коммент лежит на сервере в Амстердаме.

Но добавить такую возможность все равно можно. Я же буду переделывать скрипт, чтобы он в шаблонизатор отдавал JSON. Можно запилить простое апи для получения и отправки этого JSONа.
А о верстке и JS пусть сами думают, например.
