### ISSUE TITLE
Поддержка Куклоскрипта

### ISSUE THREAD

**Issue by georgy7** [denpamedia/minichan#11]
Как-то можно совместить его с твоей бордой?
А то я к нему уже привык, хотя только 20 минут использую.
http://www.freedollchan.org/scripts

**Comment by a-stringfield** [comment]
Думаю, не получится, т.к. он основан на парсинге html-кода страницы, как я понимаю. А взять хтмл вакабы не получится, т.к. у нас бэкенд будет передавать данные не в шаблонизатор, а в js, который уже будет расставлять их на странице.
Но, думаю, реализовать самые популярные функции куклоскрипта будет вполне возможно.

**Comment by georgy7** [comment]
Круто.
