### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by r00takaspin** [denpamedia/minichan#3]
Привет, сделал тебе вывод CSS и JS через компиляцию в ассеты (через webassets), добавь меня в контрибуторы и я пушну ветвь assets, потом примешь пул реквест.

**Comment by a-stringfield** [comment]
Добавил.

**Comment by r00takaspin** [comment]
залил, можно мерджить

**Comment by a-stringfield** [comment]
Кстати, я думаю сделать, чтобы контроллер отдавал не итератор (это, конечно, pythonic, но АПИ с итераторами не запилить), а JSON.
Это ничего в твоем коммите не сломает?
Json будет примерно таким:
{
    "op_list": [{'subject': 'Hello', 'body': 'Hello World!', 'creation_time': '07.4.2014 13:42:55'},
    {'subject': '', 'body': 'There is one girl', 'creation_time': '07.4.2014 14:04:01'},
    {'subject': '', 'body': 'I like to fap.', 'creation_time': '07.4.2014 14:32:21'}]
}

**Comment by r00takaspin** [comment]
вроде ничего не должно поломать - надо тесты запилить

**Comment by a-stringfield** [comment]
С тестами я еще не разобрался :)
Буду сегодня доки боттла курить.
