### ISSUE TITLE
Залить рабочую версию на heroku

### ISSUE THREAD

**Issue by r00takaspin** [denpamedia/minichan#5]
Гайд по переносу python приложений на heroku:
https://devcenter.heroku.com/articles/getting-started-with-python

надо сделать пример рабочей версии чана на heroku или другой другой бесплатной платформе, для тестирования и для того чтобы было что показать.

**Comment by a-stringfield** [comment]
Я на DigitalOcean держу. Просто отключил пока. Сейчас включу.
http://188.226.229.15:8080/b

**Comment by r00takaspin** [comment]
ага, вижу, чем деплоишься?

**Comment by a-stringfield** [comment]
SCPом. Как-то не найс. Можешь что-нибудь посоветовать?

**Comment by r00takaspin** [comment]
я деплоюсь capistrano в своих руби проектах, можно юзать либо его, либо что-то похожее на питоне

**Comment by a-stringfield** [comment]
Да, надо поискать что-нибудь более функциональное, чем простое копирование через ssh.
А ты не разбираешься в wsgi-серверах? Можешь посоветовать что-нибудь простое и легкое? Чтобы через pip скачал - и оно само работает.

**Comment by r00takaspin** [comment]
К сожалению, не разбираюсь. Надо погуглить и сравнить.

**Comment by a-stringfield** [comment]
Окей, буду разбираться.
