### ISSUE TITLE
контакты

### ISSUE THREAD

**Issue by r00takaspin** [denpamedia/minichan#7]
скинь свой скайп плиз на r00t@mailinator.com, думаю надо составить список фич которые надо внедрить

**Comment by a-stringfield** [comment]
Написал на почту.
Плюс, сделал страничку в вики, посмотри, можешь ли ты туда постить. Вроде, должна быть такая возможность.
https://github.com/a-stringfield/minichan/wiki

**Comment by r00takaspin** [comment]
ага,нашел, спасибо, создал страничку:
https://github.com/a-stringfield/minichan/wiki/Features
